name: API Testing Deployment CI Pipeline

on: [push, pull_request]

jobs:
  run-api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Bước 1 - Lấy mã nguồn từ GitHub về máy ảo Linux
        uses: actions/checkout@v4

      - name: Bước 2 - Thiết lập môi trường Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Bước 3 - Cài đặt các thư viện liên quan
        run: npm install

      - name: Bước 4 - Cài đặt Newman toàn cục trên máy ảo
        run: npm install -g newman newman-reporter-htmlextra

      - name: Bước 5 - Chờ Server lên hẳn rồi mới Tự Động Chạy Test
        run: npx start-server-and-test start http://127.0.0.1:3000 test:newman

      - name: Bước 6 - Đẩy file báo cáo HTML lên thành kết quả trên GitHub Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Ke-Qua-Kiem-Thu-API
          path: artifact-report.html