name: API Testing Deployment CI Pipeline

on: [push, pull_request]

jobs:
  run-api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Bước 1 - Lấy mã nguồn từ GitHub về máy ảo Linux
        uses: actions/checkout@v4

      - name: Bước 2 - Thiết lập môi trường Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Bước 3 - Cài đặt các thư viện liên quan
        run: npm install

      - name: Bước 4 - Cài đặt Newman toàn cục trên máy ảo
        run: npm install -g newman newman-reporter-htmlextra

      - name: Bước 5 - Bật Server ngầm VÀ Chạy Test đồng thời (Có In Log Debug)
        run: |
          node server.js > server.log 2>&1 &
          echo "Đang chờ 5 giây cho Server lên hẳn..."
          sleep 5
          echo "=== NHẬT KÝ ĐĂNG KÝ CỦA SERVER ==="
          cat server.log
          echo "=================================="
          newman run tests/collection.json -d tests/data.json -r cli,htmlextra --reporter-htmlextra-export artifact-report.html

      - name: Bước 6 - Đẩy file báo cáo HTML lên thành kết quả trên GitHub Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Ke-Qua-Kiem-Thu-API
          path: artifact-report.html